name: 'Publish subrepo'
description: 'Publish a mirror repo from a given subdirectory in this repo'
inputs:
  working_directory:
    description: "Path within the repo to the folder where root of the mirror repo should be"
    required: true
    default: "."
runs:
  using: "docker"
  image: "Dockerfile"
