name: 'Publish subrepo'
description: 'Publish a mirror repo from a given subdirectory in this repo'
inputs:
  working-directory:
    description: "Path within the repo to the folder where root of the mirror repo should be"
    required: true
    default: "."
runs:
  using: "composite"
  steps:
    - name: make sure we are on main
      shell: bash
      run: |
        BRANCH="$(git branch --show-current)"
        if [[ "$BRANCH" != "main" ]]; then
          echo 'Cannot publish subrepo on another branch than main';
          exit 1;
        fi

    - name: create new git repo in subfolder and push
      run: |
        git init -b main
        # TODO: fix this:
        # git push ${{ github.repositoryUrl }}-${{ inputs.working-directory }} main:main
      shell: bash
      working-directory: ${{ inputs.working-directory }}
