name: 'Publish subrepo'
description: 'Publish a mirror repo from a given subdirectory in this repo'
inputs:
  github-token:
    description: "GitHub access token used for pushing to the new repo"
    required: true
  working-directory:
    description: "Path within the repo to the folder where root of the mirror repo should be"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
