name: 'Publish subrepo'
description: 'Publish a mirror repo from a given subdirectory in this repo'
inputs:
  working-directory:
    description: "Path within the repo to the folder where root of the mirror repo should be"
    required: true
    default: "."
runs:
  using: "composite"
  steps:
    - name: create new git repo in subfolder and push
      if: github.ref_name == 'main'
      run: |
        git init -b main
        git add .
        git commit --message "Update ${{ github.repository }}-${{ inputs.working-directory }} from ${{ github.repository }}"
        git push git@github.com:${{ github.repository }}-${{ inputs.working-directory }}.git main:main
      shell: bash
      working-directory: ${{ inputs.working-directory }}
