name: Publish subrepo/mirror

# designed to be run in the https://github.com/cucumber/action-publish-subrepo-test-monorepo/ repo
on:
  workflow_call:
    secrets:
      PUSH_TOKEN:
        required: true

jobs:
  publish-to-existing-subrepo:
    name: Publish to an existing subrepo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with: 
          fetch-depth: '0'
      - name: update the 'a-subfolder' folder with something unique
        run: |
          echo ${{ github.run_number }} > a-subfolder/a-file
      - name: commit changes to monorepo and push
        run: |
          git config --global user.name 'Monorepo user'
          git config --global user.email 'monorepo-user@noreply.github.com'
          git add a-subfolder/a-file
          git commit -m "Update monorepo file in GitHub Actions run number ${{ github.run_number }}"
          git push origin
          git tag v${{ github.run_number }}
          git push --tags
      - name: Garbage collect so that git-filter-repo doesn't complain
        run: git gc
      - uses: cucumber/action-publish-subrepo@main
        with:
          working-directory: "a-subfolder"
          github-token: ${{ secrets.PUSH_TOKEN }}
          create-subrepo-if-missing: false
      - name: check that the subrepo contains our update from step 2
        run: |
          url=https://api.github.com/repos/cucumber/action-publish-subrepo-test-monorepo-a-subfolder/contents/a-file
          json=$(curl --fail -H "Accept: application/vnd.github+json" $url)
          body=$(echo "$json" | jq --raw-output '.content' | base64 -d)
          if [[ "$body" != "${{ github.run_number }}" ]]; then
            echo "expected $body to equal ${{ github.run_number }}"
            exit 1
          fi
      - name: check that the subrepo contains the tag
        run: |
          url=https://api.github.com/repos/cucumber/action-publish-subrepo-test-monorepo-a-subfolder/tags
          json=$(curl --fail -H "Accept: application/vnd.github+json" $url)
          tags=($(echo "$json" | jq --raw-output '.[] .name'))
          expected_tag="v${{ github.run_number }}"
          if [[ ! $(printf '%s\0' "${tags[@]}" | grep -F -x -z -- "$expected_tag") ]]; then
            echo "expected tags to include $expected_tag but was: $tags"
            exit 1
          fi

  publish-to-missing-subrepo:
    name: Attempt to publish to a repo that doesn't exist yet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: delete subrepo if it exists
        run: |
          if [[ $(gh repo list cucumber | grep cucumber/action-publish-subrepo-test-monorepo-another-subfolder) ]]; then
            gh repo delete cucumber/action-publish-subrepo-test-monorepo-another-subfolder --confirm
          fi
        env:
          GH_TOKEN: ${{ secrets.PUSH_TOKEN }}
      - name: Create subfolder for missing subrepo
        run: |
          mkdir another-subfolder
          touch another-subfolder/another-file
          git add another-subfolder
          git config user.email "gitbot@github.com"
          git config user.name "$GITHUB_ACTOR"
          git commit --message "Add another-subfolder"
      - uses: cucumber/action-publish-subrepo@main
        id: run-action
        continue-on-error: true
        with:
          working-directory: 'another-subfolder'
          github-token: ${{ secrets.PUSH_TOKEN }}
          create-subrepo-if-missing: false
      - name: expect failure
        if: steps.run-action.outcome == 'success'
        run: echo "Expected to fail!" && exit 1
