name: Publish subrepo/mirror

# designed to be run in the https://github.com/cucumber/action-publish-subrepo-test-monorepo/ repo
on:
  workflow_call:
    secrets:
      PUSH_TOKEN:
        required: true

jobs:
  publish-subrepo:
    name: Publish to an existing subrepo with no `main` branch yet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: remove existing main branch from target subrepo
        run: |
          git push https://${{ secrets.PUSH_TOKEN }}@github.com/cucumber/action-publish-subrepo-test-monorepo-a-subfolder :refs/heads/main 
      - name: update the 'a-subfolder' folder with something unique
        run: |
          echo ${{ github.run_number }} > a-subfolder/a-file
      - name: commit changes to monorepo and push
        run: |
          git config --global user.name 'Monorepo user'
          git config --global user.email 'monorepo-user@noreply.github.com'
          git add a-subfolder/a-file
          git commit -m "Update monorepo file in GitHub Actions run number ${{ github.run_number }}"
          git push origin
      - uses: cucumber/action-publish-subrepo@main
        with:
          working-directory: "a-subfolder"
          github-token: ${{ secrets.PUSH_TOKEN }}
      - name: check that the subrepo contains our update from step 2
        run: |
          url=https://api.github.com/repos/cucumber/action-publish-subrepo-test-monorepo-a-subfolder/contents/a-file
          json=$(curl --fail -H "Accept: application/vnd.github+json" $url)
          body=$(echo "$json" | jq --raw-output '.content' | base64 -d)
          if [[ "$body" != "${{ github.run_number }}" ]]; then
            echo "expected $body to equal ${{ github.run_number }}"
            exit 1
          fi
  attempt-publish-to-non-existent-repo:
    name: Attempt to publish to a repo that doesn't exist 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create another subfolder (with no existing matching subrepo)
        run: |
          mkdir another-subfolder
          touch another-subfolder/another-file
          git add another-subfolder
          git config user.email "gitbot@github.com"
          git config user.name "$GITHUB_ACTOR"
          git commit --message "Add another-subfolder"
      - uses: cucumber/action-publish-subrepo@main
        with:
          working-directory: 'another-subfolder'
          github-token: ${{ secrets.PUSH_TOKEN }}
        id: run-action
        continue-on-error: true
      - name: expect failure
        if: steps.run-action.outcome == 'success'
        run: echo "Expected to fail!" && exit 1