name: Publish subrepo/mirror

# designed to be run in the https://github.com/cucumber/action-publish-subrepo-test-monorepo/ repo
workflow_call:

jobs:
  publish-subrepo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: update the 'a-subfolder' folder with something unique
        run: |
          echo ${{ github.run_number }} > a-subfolder/a-file
      - name: commit changes to monorepo and push
        run: |
          git config --global user.name 'Monorepo user'
          git config --global user.email 'monorepo-user@noreply.github.com'
          git add a-subfolder/a-file
          git commit -m "Update monorepo file in GitHub Actions run number ${{ github.run_number }}"
          git push origin
      - uses: cucumber/action-publish-subrepo@main
        with:
          working-directory: "a-subfolder"
      - name: check that the subrepo contains our update from step 2
        run: |
          json=$(curl --silent --fail -H "Accept: application/vnd.github+json" https://api.github.com/repos/cucumber/action-publish-subrepo-test-monorepo/contents/a-subfolder/a-file)
          body=$(echo "$json" | jq --raw-output '.content' | base64 -d)
          if [[ "$body" != ${{ github.run_number }} ]]; do
            echo "expected $body to equal ${{ github.run_number }}"
            exit 1
          fi