name: Unit tests

on:
  push:

permissions: {}

jobs:
  run-unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: python3 -m pip install --user git-filter-repo
      - run: ./test
